spring:
  application:
    name: email-sender
  mail:
    host: localhost
    #username: somename@gmail.com  # your gmail username
    #password: some-password-app  # your gmail app password
    port: 25
    #properties:
    #  mail:
    #    smtp:
    #      auth: true
    #      connectiontimeout: 5000
    #      starttls:
    #        enable: true
    #        required: true
    #      timeout: 5000
    #      writetimeout: 5000

myapp:
  sometask: true


  #java -Duser.timezone=Europe/Athens -jar spring-core-4-0.0.1-SNAPSHOT.jar
  #